refactor snapshot to use shared infromer and versioned client
kubernetes-incubator/external-storage pull request #676
Opened 2018-03-20 08:03 UTC by wackxu

fix https://github.com/kubernetes-incubator/external-storage/issues/644

/assign @rootfs @tsmetana @jsafrane

2018-03-22 06:56 UTC, wackxu commented
@rootfs @tsmetana @jsafrane PTAL

2018-03-28 14:15 UTC, tsmetana requested changes
The new code generation and verification issues should be fixed first.

2018-03-28 14:15 UTC, tsmetana commented on hack/update-generated-code.sh
> +#   --go-header-file ${SCRIPT_ROOT}/hack/custom-boilerplate.go.txt
I failed to run hack/update-generated-code.sh successfully. It spits this and ends with error:
```
# github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/informer-gen/args
/home/tsmetana/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/informer-gen/args/args.go:38:31: args.Default().WithoutDefaultFlagParsing undefined (type *args.GeneratorArgs has no field or method WithoutDefaultFlagParsing)
# github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/defaulter-gen/args
/home/tsmetana/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/defaulter-gen/args/args.go:32:31: args.Default().WithoutDefaultFlagParsing undefined (type *args.GeneratorArgs has no field or method WithoutDefaultFlagParsing)
# github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/client-gen/args
/home/tsmetana/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/client-gen/args/args.go:55:31: args.Default().WithoutDefaultFlagParsing undefined (type *args.GeneratorArgs has no field or method WithoutDefaultFlagParsing)
# github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/lister-gen/args
/home/tsmetana/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/lister-gen/args/args.go:33:31: args.Default().WithoutDefaultFlagParsing undefined (type *args.GeneratorArgs has no field or method WithoutDefaultFlagParsing)
# github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/deepcopy-gen/args
/home/tsmetana/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/code-generator/cmd/deepcopy-gen/args/args.go:32:31: args.Default().WithoutDefaultFlagParsing undefined (type *args.GeneratorArgs has no field or method WithoutDefaultFlagParsing)
```
Not sure what exactly is wrong but the code generation definitely works in the master branch... Obviously the resulting code does not work...

2018-03-28 14:15 UTC, tsmetana commented on hack/verify-codegen.sh
> +fi
Again: there are already various verify-* scripts in the tree (see the boilerplate.go.txt comment).

2019-06-22 06:45 UTC, closed without merging